repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.11.8"
  hooks:
    - id: ruff
      name: ruff linting
    - id: ruff-format
      name: ruff formatting

- repo: https://github.com/nbQA-dev/nbQA
  rev: "1.9.1"
  hooks:
    - id: nbqa-ruff
      name: nbqa ruff linting
      args: [--fix]
    - id: nbqa-ruff-format
      name: nbqa ruff formatting

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v5.0.0'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout
    name: notebook stripping
    args: [--extra-keys=metadata.language_info.version]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'
  hooks:
  - id: mypy
    additional_dependencies:
    - jax
    args:
    - --strict
    - --show-error-codes
    - --enable-error-code=ignore-without-code
    - --allow-untyped-calls
    files: ^src/visu_hlo/
